name: Build and Deploy Front-End MI EMPLEO

on:
  push:
    branches: ["main"]

env:
  APP_NAME_FOR_PM2: 'fr-miempleo'

jobs:
  build-and-deploy:
    timeout-minutes: 10
    strategy:
      matrix:
        runner: [ main-server, res-server]
        include:
          - env_name: Production
            node_version: 20.x
            env_file: .env

    runs-on: ${{ matrix.runner }}
    environment: ${{ matrix.env_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # solo el commit actual
          clean: false # no borra los archivos

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Create .env
        run: |
          cat << EOF > ${{ matrix.env_file }}
          NEXTCLOUD_SERVER=${{ vars.NEXTCLOUD_SERVER }}
          NEXTCLOUD_ENDPOINT=${{ vars.NEXTCLOUD_ENDPOINT }}
          NEXTCLOUD_USERNAME=${{ vars.NEXTCLOUD_USERNAME }}
          NEXTCLOUD_TOKEN=${{ secrets.NEXTCLOUD_TOKEN }}
          NEXTCLOUD_FOLDER=${{ vars.NEXTCLOUD_FOLDER }}
          EOF

      - name: Install Dependencies
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Create ecosystem.config.cjs file
        run: |
          cat << EOF > ecosystem.config.cjs
          module.exports = {
            name: '${{ env.APP_NAME_FOR_PM2 }}',
            script: 'node_modules/next/dist/bin/next',
            autorestart: true,
            watch: false,
            args: 'start -p 4016',
            ignore_watch: ["node_modules", "public", "dist"],
          }
          EOF

      - name: Start or restart PM2
        run: |
          pm2 start ecosystem.config.cjs || pm2 restart ${{ env.APP_NAME_FOR_PM2 }}
          pm2 save

      - name: Notify deployment
        run: |
          echo "Despliegue del Frontend en el entorno ${{ matrix.env_name }}, en el runner ${{ matrix.runner }}, por: ${{ github.actor }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Propietario: ${{ github.repository_owner }}"
